projeto/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("", include("recipes.urls")),
    path("admin/", admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

recipes/urls.py
from django.urls import path

from . import views

# recipes:recipe
app_name = 'recipes'

urlpatterns = [
    # path('home/', views.index, name="index"),
    # path('about/', views.about, name="about"),
    # path('contact/', views.contact, name="contact"),
    path('', views.index, name="index"),
    path('recipes/category/<int:category_id>/', views.category, name="category"),
    path('recipes/<int:id>/', views.recipe, name="recipe"),
]

recipes/models.py
from django.contrib.auth.models import User
from django.db import models


# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=65)

    def __str__(self):
        return self.name


class Recipe(models.Model):
    title = models.CharField(max_length=65)
    description = models.CharField(max_length=165)
    slug = models.SlugField()
    preparation_time = models.IntegerField()
    preparation_time_unit = models.IntegerField()
    servings = models.IntegerField()
    servings_unit = models.IntegerField()
    preparation_steps = models.TextField()
    preparation_steps_is_html = models.BooleanField(default=False)
    creation_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)
    is_published = models.BooleanField(default=False)
    cover = models.ImageField(upload_to='recipes/covers/%Y/%m/%d/', blank=True, default='')
    category = models.ForeignKey(
        Category, on_delete=models.SET_NULL, null=True, blank=True, default=None
        )
    Author = models.ForeignKey(
        User, on_delete=models.SET_NULL, null=True
        )
    
    def __str__(self):
        return self.title

recipes/views.py
# from django.http import HttpResponse
from django.http import Http404
from django.shortcuts import render, get_list_or_404, get_object_or_404
from .utils.recipes.factory import make_recipe

from recipes.models import Recipe


def index(request):
    recipes = Recipe.objects.filter(is_published=True).order_by('-id')
    return render(request, 'recipes/pages/home.html', context={
        'recipes': recipes,
        # 'recipes': [make_recipe() for _ in range(10)],
    })


def recipe(request, id):
    return render(request, 'recipes/pages/recipe-view.html', context={
        'recipe': make_recipe(),
        'is_detail_page': True,
    })


def category(request, category_id):
    # recipes = Recipe.objects.filter(
    #    category__id=category_id, is_published=True).order_by('-id')
    # if not recipes:
    #    raise Http404('No found')
    recipes = get_list_or_404(
        Recipe.objects.filter(
            category__id=category_id,
            is_published=True,
        ).order_by('-id')
    )

    return render(request, 'recipes/pages/category.html', context={
        'recipes': recipes,
        'title': f'{recipes.first().category.name} - Category | '
    })

recipes/templates/recipes/pages/category.html
{% extends 'global/base.html' %}

<title>{% block title %} {% endblock title %} </title>

{% block content %}

    <div class="main-content main-content-list container">
        {% for recipe in recipes %}
            {% include 'recipes/partials/recipes.html' %}
        {% endfor %}
    </div>
{% endblock content %}

recipes/templates/recipes/pages/home.html
{% extends 'global/base.html' %}

<title>{% block title %}{% endblock title %} Home | </title>

{% block content %}

    <div class="main-content main-content-list container">
        {% for recipe in recipes %}
            {% include 'recipes/partials/recipes.html' %}
        {% endfor %}
    </div>
{% endblock content %}

recipes/templates/recipes/pages/recipe-view.html
{% extends 'global/base.html' %}

<title>{% block title %}{% endblock title %} Alterar | </title>

{% block content %}
    <div class="main-content main-content-detail container">
        {% include 'recipes/partials/recipes.html' %}
    </div>
{% endblock content %}

recipes/templates/recipes/partials/footer.html
<footer class="main-footer">
  <div class="developer">
    <a href="https://www.otaviomiranda.com.br/" target="_blank" rel="noreferrer noopener">Anaê Ross</a>
  </div>

  <div class="powered">
    <a href="https://www.djangoproject.com/" target="_blank" rel="noreferrer noopener">Powered by Django</a>
  </div>
</footer>

recipes/templates/recipes/partials/head.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-BR">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"
        integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="{% static 'recipes/css/style.css' %}">
</head>

recipes/templates/recipes/partials/header.html
    <header class="main-header-container">
        <div class="main-header container">
            <h1>
                <a class="main-logo" href="{% url 'recipes:index' %}">
                    <i class="fas fa-utensils main-logo-icon"></i>
                    <span class="main-logo-text">Recipes</span>
                </a>
            </h1>
        </div>
    </header>

recipes/templates/recipes/partials/recipes.html
<div class="recipe recipe-list-item">
<!--Verifcar se existe ou não imagem, se não existir não coloca elemento img -->
    {% if recipe.cover %}
        <div class="recipe-cover">
            <a href="{% url 'recipes:recipe' recipe.id %}"></a>
            <img src={{ recipe.cover.url }} alt="Temporário">
        </div>
    {% endif %}
    <div class="recipe-title-container">
        <h2 class="recipe-title">
            <a href="{% url 'recipes:recipe' recipe.id %}">
                {{ recipe.title }}
            </a>
        </h2>
    </div>
    <div class="recipe-author">
        <span class="recipe-author-item">
            <i class="fas fa-user"></i>
            <!-- Se usuário nao possuir nome e sobrenome preenchido ele prenche com o username-->
            {% if recipe.author.first_name %}
                {{ recipe.author.first_name }} {{ recipe.author.last_name }}
            {% else %}
                {{recipe.author.username}}
            {% endif %}
        </span>
        <span class="recipe-author-item">
            <i class="fas fa-calendar-alt"></i>
            {{ recipe.created_at|date:"d/m/Y"}} às {{recipe.created_at|date:"H:i"}}
        </span>
        {% if recipe.category is not None %}
        <span class="recipe-author-item">
            <a href="{% url 'recipes:category' recipe.category.id %}">
                <i class="fas fa-layer-group"></i>
                <span>{{ recipe.category.name}}</span>
            </a>
        </span>
        {% endif %}
    </div>
    <div class="recipe-content">
        <p>{{ recipe.preparation_steps }}</p>
    </div>

    <div class="recipe-meta-container">
        <div class="recipe-meta recipe-preparation">
            <h3 class="recipe-meta-title"><i class="fas fa-stopwatch"></i> Preparo</h3>
            <div class="recipe-meta-text">
                {{ recipe.preparation_time }} {{ recipe.preparation_time_unit }}
            </div>
        </div>
        <div class="recipe-meta recipe-servings">
            <h3 class="recipe-meta-title"><i class="fas fa-pizza-slice"></i> Porções</h3>
            <div class="recipe-meta-text">
                {{ recipe.servings }} {{ recipe.servings_unit }}
            </div>
        </div>
    </div>
    {% if is_detail_page is not True %}
        <footer class="recipe-footer">
            <a class="recipe-read-more button button-dark button-full-width" href="{% url 'recipes:recipe' recipe.id %}">
                <i class="fas fa-eye"></i>
                <span>ver mais...</span>
            </a>
        </footer>
    {% endif %}

    {% if is_detail_page is True %}
        <div class="preparation steps">
            {{ recipe.preparation_steps }}
        </div>
    {% endif %}
</div>

recipes/templates/recipes/partials/search.html
    <div class="search-container">
        <div class="container">
            <form action="" class="search-form">
                <input type="search" class="search-input" name="search">
                <button type="submit" class="search-button"><i class="fas fa-search"></i></button>
            </form>
        </div>
    </div>